export enum dashboardTableKey {
    DUTotal = "DU Total",
    Total = "Total",
    TotalPosition = "Total <br> Positions",
    OpenPositions = "Open Positions <br>(External Hiring)",
    PendingForScreen = "Pending For <br> Screening",
    ScreeningRound = "Screening <br> Round",
    TechnicalRound = "Technical - 1 <br> Round",
    TechnicalRound2 = "Technical - 2 <br> Round",
    ManagerialRound = "Managerial/Mgmt. <br> Round",
    MgmtRound = "Mgmt. Round",
    ClientRound = "Client Round",
    midwayDropCount = 'Midway Drop',
    Selected = "Selected",
    Rejected = "Rejected",
    Hold = "Hold",
    OfferedGiven = "Offered",
    OfferedDecline = "Declined",
    YTJCandidates = "Yet to Join",
    CandidatesJoined = "Joined <sup>*</sup>",
    TalentIDStatus = "Talent ID's Status",
    InterviewsStatus = "Interviews Status",
    HRSelectionStatus = "HR- Selection Status",
    CandidatesStatus = 'Candidates Status',
    dropAfterSelection = 'Drop Post Selection'

}

export enum dashboardGraphLabel {
    DUTotal = "DU Total",
    Total = "Total",
    TotalPosition = "Total Positions",
    OpenPositions = "Open Positions (TAG)",
    PendingForScreen = "Pending for Screening",
    ScreeningRound = "Screening  Round",
    TechnicalRound = "Technical Round -1",
    TechnicalRound2 = "Technical Round - 2",
    ManagerialRound = "Managerial Round",
    MgmtRound = "Mgmt. Round",
    ClientRound = "Client Round",
    midwayDropCount = 'Midway Drop',
    Selected = "Selected",
    Rejected = "Rejected",
    Hold = "Hold",
    OfferedGiven = "Offered",
    OfferedDecline = "Offered Declined",
    YTJCandidates = "Yet to Join",
    CandidatesJoined = "Candidates Joined",
    dropAfterSelection = 'Drop Post Selection'
}