export const environment = {
  production: true,
  name: 'UAT',
  locationWise:true,
  defaultSSO: false,
  isNotification:false,
  apiKey: '1234567890',
  apiBaseUrl: 'http://ipagdevserver:7070/',
  apiMainUrl: 'http://ipagdevserver:7070/info/',
  apiBaseUrlNet:'http://ipaguatvm:2221//',
  apiMainUrlNet:'http://ipaguatvm:2221//api/',
  clientId:'hfff=hg56g',
  redirect_uri:'https://ats.infogain.com/login',
  clientSecret:'hfff=hg56g',
  IOnboardAppURl:'https://ionboard.infogain.com/login',
};
